In [ ]:
import pandas as pd
import numpy as np
import os

df = pd.read_csv('../data/house_price_regression_dataset.csv')
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [ ]:
df['Building_Age']= 2026 - df['Year_Built']
df.drop('Year_Built', axis=1, inplace=True)

In [ ]:
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price,Building_Age
0,1360,2,1,0.599637,0,5,2.623829e+05,45
1,4272,3,3,4.753014,1,6,9.852609e+05,10
2,3592,1,2,3.634823,0,9,7.779774e+05,10
3,966,1,2,2.730667,1,8,2.296989e+05,49
4,4926,2,1,4.699073,0,8,1.041741e+06,33

In [ ]:
df['Total_Rooms'] = df['Num_Bedrooms'] + df['Num_Bathrooms']

In [ ]:
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price,Building_Age,Total_Rooms
0,1360,2,1,0.599637,0,5,2.623829e+05,45,3
1,4272,3,3,4.753014,1,6,9.852609e+05,10,6
2,3592,1,2,3.634823,0,9,7.779774e+05,10,3
3,966,1,2,2.730667,1,8,2.296989e+05,49,3
4,4926,2,1,4.699073,0,8,1.041741e+06,33,3

In [ ]:
os.makedirs('../data', exist_ok=True)
df.to_csv('../data/new_df.csv', index=False)
print("Saved.")

Saved.